### ISSUE TITLE
Does this support django 1.4 version

### ISSUE THREAD

**Issue by sreedharbukya** [lcd1232/django-postgrespool2#10]
I am trying to integrate this version of library for my django 1.4 version. got this error. 
`Traceback (most recent call last):
  File "./django/core/handlers/wsgi.py", line 241, in __call__
    response = self.get_response(request)
  File "./django/core/handlers/base.py", line 178, in get_response
    signals.got_request_exception.send(sender=self.__class__, request=request)
  File "./django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "./django/db/__init__.py", line 68, in _rollback_on_exception
    transaction.rollback_unless_managed(using=conn)
  File "./django/db/transaction.py", line 144, in rollback_unless_managed
    connection.rollback_unless_managed()
  File "./django/db/backends/__init__.py", line 225, in rollback_unless_managed
    self._rollback()
  File "/usr/local/lib/python2.7/dist-packages/django_postgrespool2-0.2.0-py2.7.egg/django_postgrespool2/base.py", line 105, in _rollback
AttributeError: 'DatabaseWrapper' object has no attribute 'wrap_database_errors'`

**Comment by John-Doherty01** [comment]
Not working for me on Django v2.0 also.

**Comment by lcd1232** [comment]
This version doesn't support django 1.4
