### ISSUE TITLE
pip install of django-postgrespool2==1.0.0 fails (Python 3.6)

### ISSUE THREAD

**Issue by chickahoona** [lcd1232/django-postgrespool2#15]
First thank you very much for your effort by providing this package. I have tried to install it, yet I always receive this error:

```
# pip3 install django-postgrespool2==1.0.0
Collecting django-postgrespool2==1.0.0
  Downloading https://files.pythonhosted.org/packages/85/11/16ee1747583451cd10d8db5af45e69cea471329f2d4e9fa03d9f625da128/django-postgrespool2-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6_d7q0tx/django-postgrespool2/setup.py", line 15, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1278: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6_d7q0tx/django-postgrespool2/
```

Steps to reproduce (with docker):

1. docker run -it ubuntu:18.04 /bin/bash
2. apt-get update
3. apt-get install python3-pip -y
4. pip3 install django-postgrespool2==1.0.0

**Comment by chickahoona** [comment]
I created the necessary fix. Looking forward to the official version containing this fix.
